### ISSUE TITLE
[Major] 2i search never returns

### ISSUE THREAD

**Issue by mjbrender** [drewkerrigan/riak-inverted-index-demo#12]
I'm running this demo no the [Riak App](https://github.com/basho-labs/riak-app) which runs 2.1.1 right now. Loading data and the Term-Based search options work well. 2i loads the radar spinner and never returns. 

```bash
➜  pwd
/Applications/Riak.app/Contents/Resources/riak-2.1.0
➜  bin/riak-admin status | grep -i riak_control
riak_control_version : <<"2.1.1-0-g5898c40">>
```

I'm not sure what it should look like, but I'd like to get it there.

**Comment by mjbrender** [comment]
Here's the full error when I click "Find Zombies" with 2i selected: 

```ruby
2015-06-16 11:03:26 - Riak::HTTPFailedRequest - Expected 200 from Riak but received 500. <html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,{error,{indexes_not_supported,riak_kv_bitcask_backend}}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></html>:
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/net_http_backend.rb:58:in `block (2 levels) in perform'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1413:in `block (2 levels) in transport_request'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent.rb:426:in `disable_all_tracing'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/net_http_backend.rb:56:in `block in perform'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/net_http_backend.rb:54:in `tap'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/net_http_backend.rb:54:in `perform'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/http_backend/transport_methods.rb:44:in `get'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client/http_backend.rb:248:in `get_index'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:273:in `block in get_index'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:435:in `block in recover_from'
	/Library/Ruby/Gems/2.0.0/gems/innertube-1.0.2/lib/innertube.rb:127:in `take'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:433:in `recover_from'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:286:in `http'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:131:in `backend'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/client.rb:272:in `get_index'
	/Library/Ruby/Gems/2.0.0/bundler/gems/riak-ruby-client-f04c707a369b/lib/riak/bucket.rb:162:in `get_index'
	/Users/basho/Google Drive/Basho-Dev/riak-inverted-index-demo/models/zombie.rb:61:in `search_index'
	/Users/basho/Google Drive/Basho-Dev/riak-inverted-index-demo/server.rb:42:in `block in <top (required)>'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/sinatra.rb:138:in `route_eval_with_newrelic'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/sinatra.rb:118:in `process_route_with_newrelic'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/sinatra.rb:163:in `dispatch_and_notice_errors_with_newrelic'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/sinatra.rb:149:in `block in dispatch_with_newrelic'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:352:in `perform_action_with_newrelic_trace'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/sinatra.rb:146:in `dispatch_with_newrelic'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/logger.rb:15:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/methodoverride.rb:22:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/tempfile_reaper.rb:15:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
	/Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/chunked.rb:54:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
	/Library/Ruby/Gems/2.0.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
	/Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
	/Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
	/Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
	/Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
	/Library/Ruby/Gems/2.0.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	/usr/bin/unicorn:23:in `load'
	/usr/bin/unicorn:23:in `<main>'
127.0.0.1 - - [16/Jun/2015:11:03:26 -0400] "GET /query/zip_bin/39201?start=1 HTTP/1.1" 500 301008 0.0549
I, [2015-06-16T11:03:31.110508 #84139]  INFO -- : SIGWINCH ignored because we're not daemonized
```

**Comment by mjbrender** [comment]
Ah crap, 2i isn't supported with bitcask. That's the issue. I'll set up an environment w/leveldb and go from there. Closing this ticket.
